### ISSUE TITLE
dumpprivkey "address" error

### ISSUE THREAD

**Issue by viponedream** [scash-project/scash#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

how to export the private key

### Expected behaviour

how to export the private key

### Steps to reproduce

dumpprivkey "address"
Only legacy wallets are supported by this command (code -4)

### How did you obtain Scash

Pre-built binaries

### What version of Scash are you using?

lastest

### Operating system and version

win10

**Comment by bitcartel** [comment]
Hi,

This is default Bitcoin Core behaviour now. 

Wallets use 'descriptors' so the Scash wallet (which is Bitcoin Core 26.0) will also use descriptors. More info here about Bitcoin descriptors and wallets:
- https://bitcoin.stackexchange.com/questions/107216/how-do-i-get-the-private-key-of-an-address-in-descriptor-wallets-how-to-dumppri
- https://github.com/bitcoin/bitcoin/issues/26046

Descriptors are hard to use via the command-line RPC, so would recommend you use the backup and restore wallet menu options in the GUI or via the command-line RPC.
