### ISSUE TITLE
can't connect other nodes

### ISSUE THREAD

**Issue by differs** [scash-project/scash#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

It is unclear whether it is due to the small number of full nodes or the software.

### Expected behaviour

1

### Steps to reproduce

1

### Relevant log output

1

### How did you obtain Scash

Pre-built binaries

### What version of Scash are you using?

2.0.0

### Operating system and version

ubuntu and windows

### Machine specifications

1

**Comment by magicalgirlsunite** [comment]
did you add the nodes manually? because it won't find them automatically.

**Comment by bitcartel** [comment]
Hi @differs did you add a DNS seeder? You can add them via the command-line and `scash.conf` config file.

https://github.com/scashnetwork/scash/blob/scash_master/doc/build-scash.md#config-file

```
[scash]
adddnsseed=seed.scash.one

```
