### ISSUE TITLE
When building with Depends, the configure option --disable-wallet fails

### ISSUE THREAD

**Issue by bitcartel** [scash-project/scash#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Building with configure option --disable-wallet fails.

### Expected behaviour

Build should succeed

### Steps to reproduce

Follow build steps here: https://github.com/scash-project/scash/blob/scash_master/doc/build-scash.md

Pass in option --disable-wallet to ./configure when building

./autogen.sh
make -C depends
./configure **--disable-wallet** --prefix=$PWD/depends/x86_64-pc-linux-gnu --program-transform-name='s/bitcoin/scash/g'
make

### How did you obtain Scash

Compiled from source

### What version of Scash are you using?

scash_master

### Operating system and version

Ubuntu 22.04

**Comment by says112** [comment]
Does not work on UBUNTU 20.04
![Снимок экрана (755)](https://github.com/scash-project/scash/assets/22127398/247ec899-08f3-4689-8489-227b186d0f9f)
