### ISSUE TITLE
Does not work on UBUNTU 20.04

### ISSUE THREAD

**Issue by bitcartel** [scash-project/scash#7]
Does not work on UBUNTU 20.04
![Снимок экрана (755)](https://github.com/scash-project/scash/assets/22127398/247ec899-08f3-4689-8489-227b186d0f9f)

_Originally posted by @says112 in https://github.com/scash-project/scash/issues/6#issuecomment-2035194134_

**Comment by bitcartel** [comment]
Hi @says112 a new ticket has been created for your issue. Are you running the binary release? The 1.0.4 binary release is built with Ubuntu 22.04 which uses a new version of system libraries. If you need to run on Ubuntu 20.04 please build from source.

**Comment by bitcartel** [comment]
Hi @says112 the latest 1.0.5 binary release was built on a derivative of Ubuntu 20.04 and should work. Let us know if that solves the problem for you. If not, please run `uname -a` and `lsb_release -a` and paste the results here to see exactly which version of Linux you are on.

**Comment by says112** [comment]
![Снимок экрана (760)](https://github.com/scash-project/scash/assets/22127398/a6a63255-4b31-41ca-90e2-ce5dd46a9aa5)

**Comment by says112** [comment]
Yes the latest version runs on UBUNTU 20.04 which nodes should I add to synchronize my wallet?
![Снимок экрана (761)](https://github.com/scash-project/scash/assets/22127398/ae7107e3-fda6-49ee-9517-7f9330afb77c)

**Comment by bitcartel** [comment]
It may take some time to find other nodes on the network. Did you sync up ok in the end?

**Comment by says112** [comment]
Yes
